<?php

function support_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'recipes_node_form'){
    print '<pre>';
    print_r($form);
    print '</pre>';
    //drupal_set_message("Form ID is : " . $form_id);
    $form ['menu']['#access'] = 0;
    $form['comment_settings']['#access'] = 0;
    $form['comment_settings']['comment']['#default_value'] = 1;
    $form['author']['#access'] = 0;
    $form['revision_information']['#access'] = 0;
    $form['options']['#access'] = 0;
    }
}
